console.log("Operatores in js");
console.log("Arithmetic Operatores in js");
let a=45;
let b=4;
console.log(a+b);
console.log(a-b);
console.log(a*b);
console.log(a/b);
console.log(a%b);
console.log(a++);
console.log(a--);
console.log(--a);
console.log(--b);
console.log(++b);
console.log(b++);

console.log("Assignment Operatores in js");
c=10;
console.log(c+=10);
console.log(c*=45);
console.log(c/=5);

console.log("Comparision Operatores in js");
let comp1=10;
let comp2=20;
console.log(comp1==comp2);
console.log(comp1===comp2);
console.log(comp1!==comp2);
console.log(comp1>comp2);
console.log(comp1<comp2);
